language: objective-c
osx_image: xcode8.2
before_install:
  - gem install slather
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=sources/ConfigurationKit.xcodeproj
  - IOS_FRAMEWORK_SCHEME="ConfigurationKit iOS"
  - IOS_SDK=iphonesimulator9.3
  matrix:
    - DESTINATION="OS=9.3,name=iPhone 6S" SCHEME="$IOS_FRAMEWORK_SCHEME" SDK="$IOS_SDK"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" build test
notifications:
  slack:
    secure: fUy7u8lQYbk01yYuLvI0R9b36F9Lh/rtNHwf1JLcVXuj3A+iOiE8E6NzyIFv+49pyG7KCRRaOyh5U/d8QCqsGelSn+RYHcYWmxmIo/sjynisBNDsU3BenfzZBKv4fhtiXn7WylwrgY5I96NOjTWoFvnLX/pncFDYc3ITFiE2j0M=
after_success:
  - slather coverage --input-format profdata -i ".*Tests.*" --scheme "ConfigurationKit iOS" sources/ConfigurationKit.xcodeproj
  - bash <(curl -s https://codecov.io/bash) -f cobertura.xml
